else if for failed

diff --git a/.github/workflows/main_todo-web-demo-internalweb.yml b/.github/workflows/main_todo-web-demo-internalweb.yml
--- a/.github/workflows/main_todo-web-demo-internalweb.yml
+++ b/.github/workflows/main_todo-web-demo-internalweb.yml
@@ -99,6 +99,9 @@ jobs:
               if [[ "$STATUS" == "\"Succeeded\"" ]]; then
                   echo "Deployment succeeded"
                   break
+              else if [[ "$STATUS" == "\"Failed\"" ]]; then
+                echo "Deployment failed"
+                exit 1
               else
                 echo "Deployment state: $STATUS..."
                 sleep 5
